### ISSUE TITLE
How to get more Voice Type List?

### ISSUE THREAD

**Issue by CloverTran1** [kuwacom/CapCut-TTS#10]
First I thank you for this wonderful application.
I want to ask you about how to get voice list type for languages ​​other than Japanese?
Thank you very much!

**Comment by kuwacom** [comment]
Thank you for using!

I am using only the Japanese version, so I don't know how the international version works, but I requested each voice and checked its communication (websocket) to get the voice ID.
However, there were some hidden IDs that could not be checked that way, so I went and typed the IDs in sequential numbers and did my best to find them.

If you do the same, you should be able to get the English version of speaker!
Good luck!
