### ISSUE TITLE
ENV Key

### ISSUE THREAD

**Issue by blkluv** [kuwacom/CapCut-TTS#4]
Can you help me with the CapCut TTS rapper API ENV key by showing examples?

**Comment by kuwacom** [comment]
As I wrote in Twitter DM, it is as follows.


The `Sign` is a hexadecimal number like this: `1a1234be5d678e`
`Device-Time` is an integer like this: `123456789`

These values ​​are included in the request to the `token/` endpoint when logging into CapCut, as shown in the image.
Please check using devtools such as Chrome.
https://github.com/kuwacom/CapCut-TTS/blob/main/image/capcut.png

The JWT token at the time of a request is generated based on `Device-Time`, so once you obtain it, there is no need to change it in the future. (maybe)
